version: "3.8"

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=NegocioModel.settings
      - DJANGO_ENVIRONMENT=development # Marca el entorno como desarrollo
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=el_escorial
      - DB_USER=administrador
      - DB_PASSWORD=Administrador
      - DB_HOST=db
      - DB_PORT=3306
      - DB_OPTIONS_INIT_COMMAND=SET sql_mode='STRICT_ALL_TABLES'
      - DB_OPTIONS_CHARSET=utf8mb4
      - DEBUG=True
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_persistent_data:/var/lib/mysql
      - ./bulk_data.sql:/docker-entrypoint-initdb.d/bulk_data.sql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=el_escorial
      - MYSQL_USER=administrador
      - MYSQL_PASSWORD=Administrador
      - MYSQL_ROOT_PASSWORD=PasswordRoot
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="STRICT_ALL_TABLES"

volumes:
  mysql_persistent_data:
    external: true
