# Generated by Django 4.1 on 2024-12-01 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_refactor_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Stock del repuesto ')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cantidad',
                'verbose_name_plural': 'Cantidades',
                'db_table': 'cantidad',
            },
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='stock',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='cantidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.cantidad'),
        ),
    ]
