# Generated by Django 4.1 on 2024-12-01 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_cantidad_remove_repuesto_stock_repuesto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0'), django.core.validators.MaxValueValidator(99999999, message='El precio excede lo permitido')], verbose_name='Precio'),
        ),
        migrations.DeleteModel(
            name='Cantidad',
        ),
    ]
