# Generated by Django 4.1 on 2024-12-02 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0007_create_stock_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='tipo_operacion',
            field=models.CharField(choices=[('INGRESO', 'Ingreso de existencias'), ('MERMA', 'Registro de merma'), ('PEDIDO', 'Asignación a pedido'), ('RESTITUCION', 'Restitución de pedido')], max_length=20),
        ),
    ]
