# Generated by Django 4.1 on 2024-12-02 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0009_stockoperation_tipo_operacion'),
    ]

    operations = [
        # Modificamos el campo cantidad para agregar el validador
        migrations.AlterField(
            model_name='stockoperation',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser mayor a 0')]),
        ),
        # Actualizamos el campo documento_referencia existente
        migrations.AlterField(
            model_name='stockoperation',
            name='documento_referencia',
            field=models.CharField(blank=True, help_text='Número de documento asociado (ej: factura, guía de despacho)', max_length=50),
        ),
    ]
