# Generated by Django 4.1 on 2024-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0010_stockoperation_documento_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoperation',
            name='tipo_operacion',
            field=models.CharField(choices=[('INGRESO', 'Ingreso de existencias'), ('MERMA', 'Registro de merma'), ('PEDIDO', 'Asignación a pedido'), ('RESTITUCION', 'Restitución de pedido')], max_length=30),
        ),
    ]
