# Generated by Django 4.1 on 2024-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0011_alter_stockoperation_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
