# Generated by Django 4.1 on 2024-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0012_repuesto_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_view_all_pedidos', 'Puede ver todos los pedidos'), ('can_create_pedidos', 'Puede crear pedidos'), ('can_edit_pedidos', 'Puede editar pedidos'), ('can_delete_pedidos', 'Puede eliminar pedidos'), ('can_cancel_pedidos', 'Puede cancelar pedidos'), ('can_confirm_pedidos', 'Puede confirmar pedidos'), ('can_mark_as_delivered', 'Puede marcar pedidos como entregados'), ('can_view_pedidos_reports', 'Puede ver reportes de pedidos'), ('can_export_pedidos', 'Puede exportar pedidos'), ('can_manage_own_pedidos', 'Puede gestionar sus propios pedidos')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'ordering': ['pedido', 'repuesto__nombre'], 'permissions': [('can_view_all_items', 'Puede ver todos los items de pedidos'), ('can_add_items', 'Puede añadir items a pedidos'), ('can_modify_items', 'Puede modificar items de pedidos'), ('can_delete_items', 'Puede eliminar items de pedidos'), ('can_modify_prices', 'Puede modificar precios de items'), ('can_view_item_history', 'Puede ver historial de items')], 'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'permissions': [('can_view_all_repuestos', 'Puede ver todos los repuestos'), ('can_view_stock', 'Puede ver el stock de repuestos'), ('can_view_prices', 'Puede ver los precios'), ('can_create_repuestos', 'Puede crear repuestos'), ('can_edit_repuestos', 'Puede editar repuestos'), ('can_delete_repuestos', 'Puede eliminar repuestos'), ('can_manage_stock', 'Puede gestionar el stock'), ('can_modify_prices', 'Puede modificar precios'), ('can_activate_repuestos', 'Puede activar/desactivar repuestos'), ('can_manage_images', 'Puede gestionar imágenes de repuestos'), ('can_export_repuestos', 'Puede exportar repuestos'), ('can_view_reports', 'Puede ver reportes de repuestos'), ('can_view_stock_history', 'Puede ver historial de stock')], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nombre'], 'permissions': [('can_view_all_tipos', 'Puede ver todos los tipos de repuestos'), ('can_create_tipos', 'Puede crear tipos de repuestos'), ('can_edit_tipos', 'Puede editar tipos de repuestos'), ('can_delete_tipos', 'Puede eliminar tipos de repuestos'), ('can_manage_tipos', 'Puede gestionar completamente los tipos'), ('can_export_tipos', 'Puede exportar tipos de repuestos')], 'verbose_name': 'Tipo de Repuesto', 'verbose_name_plural': 'Tipos de Repuestos'},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='tiendaApp_p_estado_d57655_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_creacion'], name='tiendaApp_p_fecha_c_bc3c52_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='tiendaApp_p_cliente_bce99f_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoitem',
            index=models.Index(fields=['pedido', 'repuesto'], name='pedido_repuesto_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigoRepuesto'], name='repuesto_codigoR_271c54_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['nombre'], name='repuesto_nombre_f4f7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['activo', 'stock'], name='repuesto_search_idx'),
        ),
        migrations.AddIndex(
            model_name='tipo',
            index=models.Index(fields=['nombre'], name='tipo_nombre_eb3976_idx'),
        ),
        migrations.AddIndex(
            model_name='tipo',
            index=models.Index(fields=['creado'], name='tipo_creado_a1c6e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['PENDIENTE', 'CONFIRMADO', 'ENTREGADO', 'CANCELADO'])), name='valid_estado_pedido'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='positive_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(check=models.Q(('precio_unitario__gt', 0)), name='positive_precio'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.UniqueConstraint(fields=('pedido', 'repuesto'), name='unique_repuesto_per_pedido'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.UniqueConstraint(fields=('codigoRepuesto',), name='unique_repuesto_codigo'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(check=models.Q(('precio__gt', 0)), name='positive_precio_repuesto'),
        ),
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='non_negative_stock'),
        ),
        migrations.AddConstraint(
            model_name='tipo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_tipo_nombre'),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='tiendaApp_pedido',
        ),
        migrations.AlterModelTable(
            name='pedidoitem',
            table='tiendaApp_pedidoitem',
        ),
    ]
